//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStorageService")]
    public interface IStorageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/PutString", ReplyAction="http://tempuri.org/IStorageService/PutStringResponse")]
        void PutString(string id, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/PutString", ReplyAction="http://tempuri.org/IStorageService/PutStringResponse")]
        System.Threading.Tasks.Task PutStringAsync(string id, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetString", ReplyAction="http://tempuri.org/IStorageService/GetStringResponse")]
        string GetString(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetString", ReplyAction="http://tempuri.org/IStorageService/GetStringResponse")]
        System.Threading.Tasks.Task<string> GetStringAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStorageServiceChannel : TesterApp.ServiceReference1.IStorageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceClient : System.ServiceModel.ClientBase<TesterApp.ServiceReference1.IStorageService>, TesterApp.ServiceReference1.IStorageService {
        
        public StorageServiceClient() {
        }
        
        public StorageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PutString(string id, string data) {
            base.Channel.PutString(id, data);
        }
        
        public System.Threading.Tasks.Task PutStringAsync(string id, string data) {
            return base.Channel.PutStringAsync(id, data);
        }
        
        public string GetString(string id) {
            return base.Channel.GetString(id);
        }
        
        public System.Threading.Tasks.Task<string> GetStringAsync(string id) {
            return base.Channel.GetStringAsync(id);
        }
    }
}
